export default [
  "https://storage.googleapis.com/sounds-decibelduck-com/ogg/180828__32cheeseman32__swordclash09.ogg",
  "https://storage.googleapis.com/sounds-decibelduck-com/ogg/185549__crazyduckman__a-quack.ogg",
  "https://storage.googleapis.com/sounds-decibelduck-com/ogg/195568__jacobalcook__creature-roar-1.ogg",
  "https://storage.googleapis.com/sounds-decibelduck-com/ogg/274448__lorenzgillner__toilet-flushing.ogg",
  "https://storage.googleapis.com/sounds-decibelduck-com/ogg/31574__walter-odington__ship-creak.ogg",
  "https://storage.googleapis.com/sounds-decibelduck-com/ogg/319590__hybrid-v__shield-bash-impact.ogg",
  "https://storage.googleapis.com/sounds-decibelduck-com/ogg/345689__inspectorj__comedic-boing-a.ogg",
  "https://storage.googleapis.com/sounds-decibelduck-com/ogg/376694__daleonfire__laser.ogg",
  "https://storage.googleapis.com/sounds-decibelduck-com/ogg/398734__anthousai__owl.ogg",
  "https://storage.googleapis.com/sounds-decibelduck-com/ogg/421791__markbolden__walking-through-leaves.ogg",
  "https://storage.googleapis.com/sounds-decibelduck-com/ogg/434878__mickthemicguy__car-honking.ogg",
  "https://storage.googleapis.com/sounds-decibelduck-com/ogg/462093__matrixxx__sparkling-star-03.ogg",
  "https://storage.googleapis.com/sounds-decibelduck-com/ogg/571797__nachtmahrtv__door-slamming-hard.ogg",
  "https://storage.googleapis.com/sounds-decibelduck-com/ogg/574044__thecrow-br__arrow.ogg",
  "https://storage.googleapis.com/sounds-decibelduck-com/ogg/63318__flag2__page-turn-please-turn-over-pto-paper-turn-over.ogg",
  "https://storage.googleapis.com/sounds-decibelduck-com/ogg/110011__tuberatanka__cat-meow.ogg",
];
